apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  queues.yaml: |-
    partitions:
      - name: default
        preemption:
          enabled: true
        nodesortpolicy:
          type: binpacking
        placementrules:
          - name: User
            create: true
            parent:
              name: Provided
              create: false
            filter:
              type: allow
              groups:
                - groupA
                - groupB
          - name: Provided
            create: true
        queues:
          - name: root
            properties:
              preemption.policy: fairshare
            submitacl: "*"
            queues:
              - name: root2
                properties:
                  preemption.policy: fairshare
                resources:
                  max:
                    memory: 1000Mi
                    vcore: 1000m
                queues:
                  - name: groupA
                    properties:
                      preemption.policy: fairshare
                    resources:
                      guaranteed:
                        memory: 700Mi
                        vcore: 700m
                    queues:
                      - name: childX
                        parent: true
                        properties:
                          preemption.policy: fairshare
                        childtemplate:
                          properties:
                            preemption.policy: fairshare
                            application.sort.policy: fifo
                        resources:
                          guaranteed:
                            memory: 200Mi
                            vcore: 200m
                      - name: childY
                        parent: true
                        properties:
                          preemption.policy: fairshare
                        childtemplate:
                          properties:
                            preemption.policy: fairshare
                            application.sort.policy: fifo
                        resources:
                          guaranteed:
                            memory: 500Mi
                            vcore: 500m
                  - name: groupB
                    parent: true
                    properties:
                      preemption.policy: fairshare
                    childtemplate:
                      properties:
                        preemption.policy: fairshare
                        application.sort.policy: fifo
                    resources:
                      guaranteed:
                        memory: 300Mi
                        vcore: 300m
