apiVersion: batch/v1
kind: Job
metadata:
  name: job-child2
  namespace: default
  labels:
    applicationId: "job-child2"
    queue: "root.level1.child2"
spec:
  completions: 10
  parallelism: 10
  template:
    metadata:
      labels:
        applicationId: "job-child2"
        queue: "root.level1.child2"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: worker
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "300m"
              memory: "300Mi"