apiVersion: batch/v1
kind: Job
metadata:
  name: job-app2
  namespace: default
  labels:
    applicationId: "job-app2"
    queue: "root.root2.groupA.childY.job-app2"
spec:
  completions: 8
  parallelism: 8
  template:
    metadata:
      labels:
        applicationId: "job-app2"
        queue: "root.root2.groupA.childY.job-app2"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: worker
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
