apiVersion: batch/v1
kind: Job
metadata:
  name: job-app3
  namespace: default
  labels:
    applicationId: "job-app3"
    queue: "root.root2.groupA.childX.job-app3"
spec:
  completions: 3
  parallelism: 3
  template:
    metadata:
      labels:
        applicationId: "job-app3"
        queue: "root.root2.groupA.childX.job-app3"
    spec:
      restartPolicy: OnFailure
      containers:
        - name: worker
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
