apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  queues.yaml: |-
    partitions:
      - name: default
        scheduler:
          reservationttl: "30s"
          requireguaranteeforreservation: true
        preemption:
          preemptattemptfrequency: "5s"
        placementrules:
          - name: provided
            create: true
            parent:
              name: tag
              value: namespace
              create: true
              parent:
                name: tag
                value: namespace.parentqueue
                create: false
          - name: provided
            create: true
            parent:
              name: tag
              value: namespace
              create: true
          - name: tag
            value: namespace
            create: true
            parent:
              name: tag
              value: namespace.parentqueue
              create: false
        queues:
          - name: root
            properties:
              preemption.policy: fairshare
            submitacl: "*"
            queues:
              - name: root2
                properties:
                  preemption.policy: fairshare
                resources:
                  max:
                    memory: 1000Mi
                    vcore: 1000m
                queues:
                  - name: groupA
                    submitacl: '*'
                    properties:
                      application.sort.policy: fair
                      preemption.delay: 2s
                      preemption.policy: fairshare
                    resources:
                      guaranteed:
                        memory: 700Mi
                        vcore: 700m
                    queues:
                      - name: childX
                        parent: true
                        properties:
                          application.sort.policy: fair
                          preemption.delay: 2s
                          preemption.policy: fairshare
                        childtemplate:
                          maxapplications: 1
                          properties:
                            application.sort.policy: fair
                            preemption.delay: 2s
                            preemption.policy: fairshare
                          resources:
                            max: {pods: 10000, ephemeral-storage: 999T}
                            guaranteed: {pods: 10000, ephemeral-storage: 999T}
                        resources:
                          guaranteed:
                            memory: 200Mi
                            vcore: 200m
                      - name: childY
                        parent: true
                        properties:
                          application.sort.policy: fair
                          preemption.delay: 2s
                          preemption.policy: fairshare
                        childtemplate:
                          maxapplications: 1
                          properties:
                            application.sort.policy: fair
                            preemption.delay: 2s
                            preemption.policy: fairshare
                          resources:
                            max: {pods: 10000, ephemeral-storage: 999T}
                            guaranteed: {pods: 10000, ephemeral-storage: 999T}
                        resources:
                          guaranteed:
                            memory: 500Mi
                            vcore: 500m
                  - name: groupB
                    submitacl: '*'
                    parent: true
                    properties:
                      application.sort.policy: fair
                      preemption.delay: 2s
                      preemption.policy: fairshare
                    childtemplate:
                      maxapplications: 1
                      properties:
                        application.sort.policy: fair
                        preemption.delay: 2s
                        preemption.policy: fairshare
                      resources:
                        max: {pods: 10000, ephemeral-storage: 999T}
                        guaranteed: {pods: 10000, ephemeral-storage: 999T}
                    resources:
                      guaranteed:
                        memory: 300Mi
                        vcore: 300m
